//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Controls/Midi.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Midi : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Midi()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Midi"",
    ""maps"": [
        {
            ""name"": ""MidiInputs"",
            ""id"": ""4d7b9d0c-6f6a-4232-9d31-ab75b626573e"",
            ""actions"": [
                {
                    ""name"": ""C"",
                    ""type"": ""Button"",
                    ""id"": ""d4d3313e-de70-4d73-b880-50dafe4b34c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CSharp"",
                    ""type"": ""Button"",
                    ""id"": ""62ee006d-c703-4b4a-9d0d-b9034fef3713"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""D"",
                    ""type"": ""Button"",
                    ""id"": ""38cc72d4-296a-4989-ba57-f32fc9cb6012"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DSharp"",
                    ""type"": ""Button"",
                    ""id"": ""abfe5a2d-d541-486f-a7aa-f1c3b230dbe3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""E"",
                    ""type"": ""Button"",
                    ""id"": ""788a665f-3919-4d1e-9ea1-249f5d77a425"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""F"",
                    ""type"": ""Button"",
                    ""id"": ""23d79358-bca5-4d8f-b301-05bc2c5bfc2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FSharp"",
                    ""type"": ""Button"",
                    ""id"": ""aa74f10f-08aa-4a40-855b-bc5380d8dd9b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""G"",
                    ""type"": ""Button"",
                    ""id"": ""31902feb-6752-497f-9b19-62923dbb0477"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GSharp"",
                    ""type"": ""Button"",
                    ""id"": ""2413db0b-44b2-47df-9c17-9ee7cf302def"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""5e1b51e9-2890-49d5-ad11-32e7d2455210"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ASharp"",
                    ""type"": ""Button"",
                    ""id"": ""65088cd9-f1ab-47d9-97e8-911ce21bee0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""B"",
                    ""type"": ""Button"",
                    ""id"": ""2f606f45-7451-4603-a559-dab1fde0e811"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5a0baa2e-3052-4161-9725-be6344a11d67"",
                    ""path"": ""<MidiDevice>/note036"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""357b8cf8-4782-44ae-9cd1-d58782816cf1"",
                    ""path"": ""<MidiDevice>/note048"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e26e872-2bc9-422a-9713-47b4e5cbc106"",
                    ""path"": ""<MidiDevice>/note060"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""513c3ad2-881f-4ec1-bbc8-beddc152ed2c"",
                    ""path"": ""<MidiDevice>/note072"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3944a1c5-3a9e-4ac4-b0b8-58071bfd43c7"",
                    ""path"": ""<MidiDevice>/note050"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ea411f7-fd50-4ed4-9b5a-f694899b6665"",
                    ""path"": ""<MidiDevice>/note062"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f50d6f9-7edc-4c6a-8bbe-67171bbfcbeb"",
                    ""path"": ""<MidiDevice>/note074"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d940473-776a-4663-b723-58e146a12564"",
                    ""path"": ""<MidiDevice>/note038"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""743618a4-9b6f-437f-867a-9b8c6e11a4f4"",
                    ""path"": ""<MidiDevice>/note052"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6621b07-05b9-4ff6-abdb-8a67d0db3228"",
                    ""path"": ""<MidiDevice>/note064"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae6c4c53-84d5-4f95-a474-047c1c97f66e"",
                    ""path"": ""<MidiDevice>/note076"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3f8d580-6c60-4df1-ae51-4629db2d3251"",
                    ""path"": ""<MidiDevice>/note040"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fec323b-49f4-417a-abfc-f8306a773a5c"",
                    ""path"": ""<MidiDevice>/note037"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08d105d0-45f4-4bc9-9845-d995e3666c17"",
                    ""path"": ""<MidiDevice>/note049"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d52ae08-f9a1-481b-b44c-d9d4b6fbed79"",
                    ""path"": ""<MidiDevice>/note061"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""950f5945-b90e-453c-8f9e-871db9f8bd14"",
                    ""path"": ""<MidiDevice>/note073"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ffdba120-8c52-4db2-a456-13700cc8d93d"",
                    ""path"": ""<MidiDevice>/note051"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1862396c-35c5-40e5-90b3-df30ffcec77a"",
                    ""path"": ""<MidiDevice>/note063"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4dbfa392-0e14-4e0d-9d19-9a351f2222c4"",
                    ""path"": ""<MidiDevice>/note075"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1ca9e4d-7929-400f-a639-5beaf8f292fd"",
                    ""path"": ""<MidiDevice>/note039"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""781dd1df-bf96-4aef-abc5-061b7b56b778"",
                    ""path"": ""<MidiDevice>/note053"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67e980f6-1f43-4af1-8d23-196ac251eb66"",
                    ""path"": ""<MidiDevice>/note065"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f6f7dfb-660d-4a4b-a286-b1b80c587289"",
                    ""path"": ""<MidiDevice>/note077"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9cc25a0-772f-4900-9079-fc1e32f30440"",
                    ""path"": ""<MidiDevice>/note041"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""442719aa-6067-480c-9757-3a56b6c2755c"",
                    ""path"": ""<MidiDevice>/note054"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f13cf44-482b-472b-8314-a9c138c0e5b0"",
                    ""path"": ""<MidiDevice>/note066"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f3a9b43-6c99-4090-ad6f-89c107bcdaeb"",
                    ""path"": ""<MidiDevice>/note078"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af333685-3828-4e51-b209-6b1d4b6826cc"",
                    ""path"": ""<MidiDevice>/note042"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bccd02a0-192a-448b-8e4a-214e1b1c234c"",
                    ""path"": ""<MidiDevice>/note055"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84d50bd5-05ea-48b2-a8e0-bd9d294a302c"",
                    ""path"": ""<MidiDevice>/note067"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""609167bc-d44c-4bb2-b72c-6265cb984e59"",
                    ""path"": ""<MidiDevice>/note079"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c9061cd-31d2-4f52-82d0-ec4d662e20b8"",
                    ""path"": ""<MidiDevice>/note043"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15d78462-f41a-4267-9f0c-42176dbf13fa"",
                    ""path"": ""<MidiDevice>/note056"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6c9d9d8-6223-4436-a7cb-a4dfd9180285"",
                    ""path"": ""<MidiDevice>/note068"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a6c6ebe-ba7c-45c1-8f28-e7bd4be5bd13"",
                    ""path"": ""<MidiDevice>/note080"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9644a33d-e000-427f-94ca-10293fb8d1ee"",
                    ""path"": ""<MidiDevice>/note044"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GSharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""057ee60a-f2a5-46c3-809f-72e53ef3ef0d"",
                    ""path"": ""<MidiDevice>/note057"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd3b719a-127e-4421-bc7b-e278c1783b6b"",
                    ""path"": ""<MidiDevice>/note069"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""657fa631-89fe-40d6-bdc8-9b5a3608dc3f"",
                    ""path"": ""<MidiDevice>/note081"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c209d04-da04-4f6e-a21f-e965092ff796"",
                    ""path"": ""<MidiDevice>/note045"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""569c14f9-28c5-4114-b87e-d61c347792d3"",
                    ""path"": ""<MidiDevice>/note058"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ASharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59c92fd2-52be-47b9-a4de-87557560cf4e"",
                    ""path"": ""<MidiDevice>/note070"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ASharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b9a1964-2cf6-4109-8840-3112280e8acc"",
                    ""path"": ""<MidiDevice>/note082"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ASharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72004aa8-347d-4796-9f4c-2230329da4be"",
                    ""path"": ""<MidiDevice>/note046"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ASharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a75e7bce-a54a-4f61-a6f7-a7009a145f62"",
                    ""path"": ""<MidiDevice>/note059"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccce7b11-d74e-4020-9459-e9d8fbd85ddf"",
                    ""path"": ""<MidiDevice>/note071"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd036a33-b090-44d0-938f-22d548c95729"",
                    ""path"": ""<MidiDevice>/note083"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11474e82-a9c5-4c39-a37d-bd3e6b47a89d"",
                    ""path"": ""<MidiDevice>/note047"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MidiInputs
        m_MidiInputs = asset.FindActionMap("MidiInputs", throwIfNotFound: true);
        m_MidiInputs_C = m_MidiInputs.FindAction("C", throwIfNotFound: true);
        m_MidiInputs_CSharp = m_MidiInputs.FindAction("CSharp", throwIfNotFound: true);
        m_MidiInputs_D = m_MidiInputs.FindAction("D", throwIfNotFound: true);
        m_MidiInputs_DSharp = m_MidiInputs.FindAction("DSharp", throwIfNotFound: true);
        m_MidiInputs_E = m_MidiInputs.FindAction("E", throwIfNotFound: true);
        m_MidiInputs_F = m_MidiInputs.FindAction("F", throwIfNotFound: true);
        m_MidiInputs_FSharp = m_MidiInputs.FindAction("FSharp", throwIfNotFound: true);
        m_MidiInputs_G = m_MidiInputs.FindAction("G", throwIfNotFound: true);
        m_MidiInputs_GSharp = m_MidiInputs.FindAction("GSharp", throwIfNotFound: true);
        m_MidiInputs_A = m_MidiInputs.FindAction("A", throwIfNotFound: true);
        m_MidiInputs_ASharp = m_MidiInputs.FindAction("ASharp", throwIfNotFound: true);
        m_MidiInputs_B = m_MidiInputs.FindAction("B", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MidiInputs
    private readonly InputActionMap m_MidiInputs;
    private IMidiInputsActions m_MidiInputsActionsCallbackInterface;
    private readonly InputAction m_MidiInputs_C;
    private readonly InputAction m_MidiInputs_CSharp;
    private readonly InputAction m_MidiInputs_D;
    private readonly InputAction m_MidiInputs_DSharp;
    private readonly InputAction m_MidiInputs_E;
    private readonly InputAction m_MidiInputs_F;
    private readonly InputAction m_MidiInputs_FSharp;
    private readonly InputAction m_MidiInputs_G;
    private readonly InputAction m_MidiInputs_GSharp;
    private readonly InputAction m_MidiInputs_A;
    private readonly InputAction m_MidiInputs_ASharp;
    private readonly InputAction m_MidiInputs_B;
    public struct MidiInputsActions
    {
        private @Midi m_Wrapper;
        public MidiInputsActions(@Midi wrapper) { m_Wrapper = wrapper; }
        public InputAction @C => m_Wrapper.m_MidiInputs_C;
        public InputAction @CSharp => m_Wrapper.m_MidiInputs_CSharp;
        public InputAction @D => m_Wrapper.m_MidiInputs_D;
        public InputAction @DSharp => m_Wrapper.m_MidiInputs_DSharp;
        public InputAction @E => m_Wrapper.m_MidiInputs_E;
        public InputAction @F => m_Wrapper.m_MidiInputs_F;
        public InputAction @FSharp => m_Wrapper.m_MidiInputs_FSharp;
        public InputAction @G => m_Wrapper.m_MidiInputs_G;
        public InputAction @GSharp => m_Wrapper.m_MidiInputs_GSharp;
        public InputAction @A => m_Wrapper.m_MidiInputs_A;
        public InputAction @ASharp => m_Wrapper.m_MidiInputs_ASharp;
        public InputAction @B => m_Wrapper.m_MidiInputs_B;
        public InputActionMap Get() { return m_Wrapper.m_MidiInputs; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MidiInputsActions set) { return set.Get(); }
        public void SetCallbacks(IMidiInputsActions instance)
        {
            if (m_Wrapper.m_MidiInputsActionsCallbackInterface != null)
            {
                @C.started -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnC;
                @C.performed -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnC;
                @C.canceled -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnC;
                @CSharp.started -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnCSharp;
                @CSharp.performed -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnCSharp;
                @CSharp.canceled -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnCSharp;
                @D.started -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnD;
                @D.performed -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnD;
                @D.canceled -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnD;
                @DSharp.started -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnDSharp;
                @DSharp.performed -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnDSharp;
                @DSharp.canceled -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnDSharp;
                @E.started -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnE;
                @E.performed -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnE;
                @E.canceled -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnE;
                @F.started -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnF;
                @F.performed -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnF;
                @F.canceled -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnF;
                @FSharp.started -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnFSharp;
                @FSharp.performed -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnFSharp;
                @FSharp.canceled -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnFSharp;
                @G.started -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnG;
                @G.performed -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnG;
                @G.canceled -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnG;
                @GSharp.started -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnGSharp;
                @GSharp.performed -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnGSharp;
                @GSharp.canceled -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnGSharp;
                @A.started -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnA;
                @A.performed -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnA;
                @A.canceled -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnA;
                @ASharp.started -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnASharp;
                @ASharp.performed -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnASharp;
                @ASharp.canceled -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnASharp;
                @B.started -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnB;
                @B.performed -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnB;
                @B.canceled -= m_Wrapper.m_MidiInputsActionsCallbackInterface.OnB;
            }
            m_Wrapper.m_MidiInputsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @C.started += instance.OnC;
                @C.performed += instance.OnC;
                @C.canceled += instance.OnC;
                @CSharp.started += instance.OnCSharp;
                @CSharp.performed += instance.OnCSharp;
                @CSharp.canceled += instance.OnCSharp;
                @D.started += instance.OnD;
                @D.performed += instance.OnD;
                @D.canceled += instance.OnD;
                @DSharp.started += instance.OnDSharp;
                @DSharp.performed += instance.OnDSharp;
                @DSharp.canceled += instance.OnDSharp;
                @E.started += instance.OnE;
                @E.performed += instance.OnE;
                @E.canceled += instance.OnE;
                @F.started += instance.OnF;
                @F.performed += instance.OnF;
                @F.canceled += instance.OnF;
                @FSharp.started += instance.OnFSharp;
                @FSharp.performed += instance.OnFSharp;
                @FSharp.canceled += instance.OnFSharp;
                @G.started += instance.OnG;
                @G.performed += instance.OnG;
                @G.canceled += instance.OnG;
                @GSharp.started += instance.OnGSharp;
                @GSharp.performed += instance.OnGSharp;
                @GSharp.canceled += instance.OnGSharp;
                @A.started += instance.OnA;
                @A.performed += instance.OnA;
                @A.canceled += instance.OnA;
                @ASharp.started += instance.OnASharp;
                @ASharp.performed += instance.OnASharp;
                @ASharp.canceled += instance.OnASharp;
                @B.started += instance.OnB;
                @B.performed += instance.OnB;
                @B.canceled += instance.OnB;
            }
        }
    }
    public MidiInputsActions @MidiInputs => new MidiInputsActions(this);
    public interface IMidiInputsActions
    {
        void OnC(InputAction.CallbackContext context);
        void OnCSharp(InputAction.CallbackContext context);
        void OnD(InputAction.CallbackContext context);
        void OnDSharp(InputAction.CallbackContext context);
        void OnE(InputAction.CallbackContext context);
        void OnF(InputAction.CallbackContext context);
        void OnFSharp(InputAction.CallbackContext context);
        void OnG(InputAction.CallbackContext context);
        void OnGSharp(InputAction.CallbackContext context);
        void OnA(InputAction.CallbackContext context);
        void OnASharp(InputAction.CallbackContext context);
        void OnB(InputAction.CallbackContext context);
    }
}
