//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Controls/PianoFull.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PianoFull : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PianoFull()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PianoFull"",
    ""maps"": [
        {
            ""name"": ""Piano"",
            ""id"": ""e246c747-ba2e-4ade-81e1-7bc16b30200d"",
            ""actions"": [
                {
                    ""name"": ""C2"",
                    ""type"": ""Button"",
                    ""id"": ""8f377346-94b5-4ab7-b2ff-f0ee7049dd73"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CS2"",
                    ""type"": ""Button"",
                    ""id"": ""1d1eb6f6-e616-48b9-83c6-cf4b5fca899d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D2"",
                    ""type"": ""Button"",
                    ""id"": ""474696b2-87a9-477f-b4a8-2c1645599438"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DS2"",
                    ""type"": ""Button"",
                    ""id"": ""14e95190-3225-41c1-9ddb-7e90003b8b5d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""E2"",
                    ""type"": ""Button"",
                    ""id"": ""fae388f4-be84-4156-8672-0837f5d191cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F2"",
                    ""type"": ""Button"",
                    ""id"": ""173d5bf9-e3b6-4969-b898-f469de453b9a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FS2"",
                    ""type"": ""Button"",
                    ""id"": ""a28b2dfa-e128-49e6-9941-417441d95ab8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""G2"",
                    ""type"": ""Button"",
                    ""id"": ""a880af33-ff99-4389-8252-f52fc99cf192"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GS2"",
                    ""type"": ""Button"",
                    ""id"": ""65c9b0dc-9825-4a01-9d6c-631e4f4fdde2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A2"",
                    ""type"": ""Button"",
                    ""id"": ""8df0f05f-f33d-49d9-abf8-408afbd49b6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AS2"",
                    ""type"": ""Button"",
                    ""id"": ""e196d1ce-2def-456d-bb10-b93b38b52776"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B2"",
                    ""type"": ""Button"",
                    ""id"": ""80918a46-daec-4377-8f91-2a535c197fe8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""C3"",
                    ""type"": ""Button"",
                    ""id"": ""24595218-9223-4a26-b755-3c0f59cc14d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CS3"",
                    ""type"": ""Button"",
                    ""id"": ""5ca41a8c-2cee-4203-b979-c65340362eb6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D3"",
                    ""type"": ""Button"",
                    ""id"": ""2dda11f0-96c6-43af-ae02-fb6ca88e1842"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DS3"",
                    ""type"": ""Button"",
                    ""id"": ""d66fd956-de6f-4614-9059-9dc99a368e91"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""E3"",
                    ""type"": ""Button"",
                    ""id"": ""71b79906-166e-4ca5-91a9-916719f4a5ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F3"",
                    ""type"": ""Button"",
                    ""id"": ""2653f89f-4766-42ed-92c3-b934f8340b17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FS3"",
                    ""type"": ""Button"",
                    ""id"": ""89eaf2db-2b29-44e7-8c99-02fe55f3d817"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""G3"",
                    ""type"": ""Button"",
                    ""id"": ""9f974944-3e7e-49b9-91da-9e9635c5de18"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GS3"",
                    ""type"": ""Button"",
                    ""id"": ""b41ea186-79e3-4c27-b2eb-c1e0b4bf2ada"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A3"",
                    ""type"": ""Button"",
                    ""id"": ""5d120650-515e-4515-bc85-12bc6da62ea9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AS3"",
                    ""type"": ""Button"",
                    ""id"": ""55f70436-3e54-4976-90ab-e9d87ae7481b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B3"",
                    ""type"": ""Button"",
                    ""id"": ""1a0c001d-7b15-46e5-b44a-2da8a1049b93"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""C4"",
                    ""type"": ""Button"",
                    ""id"": ""c76e4fac-7c8f-4a21-a892-3b6fe625596a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CS4"",
                    ""type"": ""Button"",
                    ""id"": ""9c524a27-9302-43f9-a2ba-185703ac90ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D4"",
                    ""type"": ""Button"",
                    ""id"": ""f44cdef5-afae-4546-9d21-fbdb0597168e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DS4"",
                    ""type"": ""Button"",
                    ""id"": ""81735f33-97bd-4992-95db-794835d7262d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""E4"",
                    ""type"": ""Button"",
                    ""id"": ""29b7f902-4830-44dd-909c-e8573c1795f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F4"",
                    ""type"": ""Button"",
                    ""id"": ""5b60c41b-24af-4efb-b35b-40329ad39a5e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FS4"",
                    ""type"": ""Button"",
                    ""id"": ""b621a47d-5937-4698-8180-7de29415bbd5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""G4"",
                    ""type"": ""Button"",
                    ""id"": ""3ea646f4-09c7-47c5-881a-89b69cec1158"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GS4"",
                    ""type"": ""Button"",
                    ""id"": ""c1ee85fa-bf08-4b8c-be74-c2957b32eb98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A4"",
                    ""type"": ""Button"",
                    ""id"": ""e1a9e9be-9b74-4311-9c44-57355d1e79fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AS4"",
                    ""type"": ""Button"",
                    ""id"": ""9942643c-f046-4a6b-bdfb-f70654c4f8be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B4"",
                    ""type"": ""Button"",
                    ""id"": ""562ffeef-a34e-4f45-9a03-b78e3806895e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9b6a54a8-e3f2-401a-81c9-32c88dfc9746"",
                    ""path"": ""<MidiDevice>/note036"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10a17a4b-48f8-47d2-ae24-e14607e75944"",
                    ""path"": ""<MidiDevice>/note037"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CS2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27f93306-f627-4135-9fde-a9cea85a0979"",
                    ""path"": ""<MidiDevice>/note038"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6697abd8-94ab-40f9-a811-afc1a6794275"",
                    ""path"": ""<MidiDevice>/note039"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DS2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e5b9cbd-9a1e-4d9b-a785-02ce7a3e58f7"",
                    ""path"": ""<MidiDevice>/note040"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79ce2269-6061-48c0-9418-674674c678bd"",
                    ""path"": ""<MidiDevice>/note041"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b241125-744b-4c4b-ad3f-7b524f1fd7ad"",
                    ""path"": ""<MidiDevice>/note042"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FS2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62a32350-e072-41ad-b3a4-611ff191e8dc"",
                    ""path"": ""<MidiDevice>/note043"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0aebe80a-1e31-4415-965c-292388bd1286"",
                    ""path"": ""<MidiDevice>/note044"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GS2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6507946a-0ec9-454b-8701-10fbdd48470e"",
                    ""path"": ""<MidiDevice>/note045"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b684b3f8-f93c-43e0-b5dc-42c4550aa98a"",
                    ""path"": ""<MidiDevice>/note046"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AS2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1396120c-fc71-47f7-bb18-62ae340868e5"",
                    ""path"": ""<MidiDevice>/note047"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9208632b-0bc6-4477-8109-e637aa45f775"",
                    ""path"": ""<MidiDevice>/note048"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47d15ccc-af5b-4514-bf29-4dd4fb1a6a54"",
                    ""path"": ""<MidiDevice>/note049"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edfd6c89-c5d5-40da-8ab0-fa85a8cda106"",
                    ""path"": ""<MidiDevice>/note050"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e569351-dcd3-48c4-a140-719f7015165f"",
                    ""path"": ""<MidiDevice>/note051"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b64d10e-be8b-4ddc-975d-b9bc3bb9043f"",
                    ""path"": ""<MidiDevice>/note052"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f1271c1-d99f-4e93-89d9-9c36556aae01"",
                    ""path"": ""<MidiDevice>/note053"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a1a5e61-a7cd-43bb-bc31-09d6fe380e4b"",
                    ""path"": ""<MidiDevice>/note054"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c527106a-600e-48fd-9ba8-b1aab3549a5d"",
                    ""path"": ""<MidiDevice>/note055"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4def6ae-1cd8-48d6-a090-2189f9f60c46"",
                    ""path"": ""<MidiDevice>/note056"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""211b0e4a-acd4-4dcd-8f69-9ab15f465ae9"",
                    ""path"": ""<MidiDevice>/note057"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63f1570d-4aa1-4d91-be29-8ce9d93e9cc4"",
                    ""path"": ""<MidiDevice>/note058"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eca5cc36-d0a5-4342-87d7-8d84e5803df0"",
                    ""path"": ""<MidiDevice>/note059"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""532c0ad3-8688-4e28-ab13-05047eb8f899"",
                    ""path"": ""<MidiDevice>/note060"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b988f3e-96f0-43d0-9ca1-37900fbd20c3"",
                    ""path"": ""<MidiDevice>/note061"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CS4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c3eba3d-cff1-4efc-9ec1-a2c911d8e738"",
                    ""path"": ""<MidiDevice>/note062"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac4857d6-3eee-4825-892c-0b9f71e59749"",
                    ""path"": ""<MidiDevice>/note063"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DS4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02cfac35-f488-4f9d-accb-4d1401039b59"",
                    ""path"": ""<MidiDevice>/note064"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a966cde-ee93-4cfd-936f-d747755b0397"",
                    ""path"": ""<MidiDevice>/note065"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a825b3a-699d-4bbb-b6bf-fb7c3d2e7a42"",
                    ""path"": ""<MidiDevice>/note066"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FS4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41156c7f-f608-47a1-a83b-9852e6b30b8f"",
                    ""path"": ""<MidiDevice>/note067"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee985515-d700-47a6-8797-b82814a11414"",
                    ""path"": ""<MidiDevice>/note068"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GS4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5554c1df-73c1-499e-a542-e9665021a0cd"",
                    ""path"": ""<MidiDevice>/note069"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebc66f24-f491-47cd-9c49-3b3c391e37cf"",
                    ""path"": ""<MidiDevice>/note070"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AS4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7dd31ed6-c8d9-4b67-8ea3-0b2db9130b76"",
                    ""path"": ""<MidiDevice>/note071"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Piano
        m_Piano = asset.FindActionMap("Piano", throwIfNotFound: true);
        m_Piano_C2 = m_Piano.FindAction("C2", throwIfNotFound: true);
        m_Piano_CS2 = m_Piano.FindAction("CS2", throwIfNotFound: true);
        m_Piano_D2 = m_Piano.FindAction("D2", throwIfNotFound: true);
        m_Piano_DS2 = m_Piano.FindAction("DS2", throwIfNotFound: true);
        m_Piano_E2 = m_Piano.FindAction("E2", throwIfNotFound: true);
        m_Piano_F2 = m_Piano.FindAction("F2", throwIfNotFound: true);
        m_Piano_FS2 = m_Piano.FindAction("FS2", throwIfNotFound: true);
        m_Piano_G2 = m_Piano.FindAction("G2", throwIfNotFound: true);
        m_Piano_GS2 = m_Piano.FindAction("GS2", throwIfNotFound: true);
        m_Piano_A2 = m_Piano.FindAction("A2", throwIfNotFound: true);
        m_Piano_AS2 = m_Piano.FindAction("AS2", throwIfNotFound: true);
        m_Piano_B2 = m_Piano.FindAction("B2", throwIfNotFound: true);
        m_Piano_C3 = m_Piano.FindAction("C3", throwIfNotFound: true);
        m_Piano_CS3 = m_Piano.FindAction("CS3", throwIfNotFound: true);
        m_Piano_D3 = m_Piano.FindAction("D3", throwIfNotFound: true);
        m_Piano_DS3 = m_Piano.FindAction("DS3", throwIfNotFound: true);
        m_Piano_E3 = m_Piano.FindAction("E3", throwIfNotFound: true);
        m_Piano_F3 = m_Piano.FindAction("F3", throwIfNotFound: true);
        m_Piano_FS3 = m_Piano.FindAction("FS3", throwIfNotFound: true);
        m_Piano_G3 = m_Piano.FindAction("G3", throwIfNotFound: true);
        m_Piano_GS3 = m_Piano.FindAction("GS3", throwIfNotFound: true);
        m_Piano_A3 = m_Piano.FindAction("A3", throwIfNotFound: true);
        m_Piano_AS3 = m_Piano.FindAction("AS3", throwIfNotFound: true);
        m_Piano_B3 = m_Piano.FindAction("B3", throwIfNotFound: true);
        m_Piano_C4 = m_Piano.FindAction("C4", throwIfNotFound: true);
        m_Piano_CS4 = m_Piano.FindAction("CS4", throwIfNotFound: true);
        m_Piano_D4 = m_Piano.FindAction("D4", throwIfNotFound: true);
        m_Piano_DS4 = m_Piano.FindAction("DS4", throwIfNotFound: true);
        m_Piano_E4 = m_Piano.FindAction("E4", throwIfNotFound: true);
        m_Piano_F4 = m_Piano.FindAction("F4", throwIfNotFound: true);
        m_Piano_FS4 = m_Piano.FindAction("FS4", throwIfNotFound: true);
        m_Piano_G4 = m_Piano.FindAction("G4", throwIfNotFound: true);
        m_Piano_GS4 = m_Piano.FindAction("GS4", throwIfNotFound: true);
        m_Piano_A4 = m_Piano.FindAction("A4", throwIfNotFound: true);
        m_Piano_AS4 = m_Piano.FindAction("AS4", throwIfNotFound: true);
        m_Piano_B4 = m_Piano.FindAction("B4", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Piano
    private readonly InputActionMap m_Piano;
    private IPianoActions m_PianoActionsCallbackInterface;
    private readonly InputAction m_Piano_C2;
    private readonly InputAction m_Piano_CS2;
    private readonly InputAction m_Piano_D2;
    private readonly InputAction m_Piano_DS2;
    private readonly InputAction m_Piano_E2;
    private readonly InputAction m_Piano_F2;
    private readonly InputAction m_Piano_FS2;
    private readonly InputAction m_Piano_G2;
    private readonly InputAction m_Piano_GS2;
    private readonly InputAction m_Piano_A2;
    private readonly InputAction m_Piano_AS2;
    private readonly InputAction m_Piano_B2;
    private readonly InputAction m_Piano_C3;
    private readonly InputAction m_Piano_CS3;
    private readonly InputAction m_Piano_D3;
    private readonly InputAction m_Piano_DS3;
    private readonly InputAction m_Piano_E3;
    private readonly InputAction m_Piano_F3;
    private readonly InputAction m_Piano_FS3;
    private readonly InputAction m_Piano_G3;
    private readonly InputAction m_Piano_GS3;
    private readonly InputAction m_Piano_A3;
    private readonly InputAction m_Piano_AS3;
    private readonly InputAction m_Piano_B3;
    private readonly InputAction m_Piano_C4;
    private readonly InputAction m_Piano_CS4;
    private readonly InputAction m_Piano_D4;
    private readonly InputAction m_Piano_DS4;
    private readonly InputAction m_Piano_E4;
    private readonly InputAction m_Piano_F4;
    private readonly InputAction m_Piano_FS4;
    private readonly InputAction m_Piano_G4;
    private readonly InputAction m_Piano_GS4;
    private readonly InputAction m_Piano_A4;
    private readonly InputAction m_Piano_AS4;
    private readonly InputAction m_Piano_B4;
    public struct PianoActions
    {
        private @PianoFull m_Wrapper;
        public PianoActions(@PianoFull wrapper) { m_Wrapper = wrapper; }
        public InputAction @C2 => m_Wrapper.m_Piano_C2;
        public InputAction @CS2 => m_Wrapper.m_Piano_CS2;
        public InputAction @D2 => m_Wrapper.m_Piano_D2;
        public InputAction @DS2 => m_Wrapper.m_Piano_DS2;
        public InputAction @E2 => m_Wrapper.m_Piano_E2;
        public InputAction @F2 => m_Wrapper.m_Piano_F2;
        public InputAction @FS2 => m_Wrapper.m_Piano_FS2;
        public InputAction @G2 => m_Wrapper.m_Piano_G2;
        public InputAction @GS2 => m_Wrapper.m_Piano_GS2;
        public InputAction @A2 => m_Wrapper.m_Piano_A2;
        public InputAction @AS2 => m_Wrapper.m_Piano_AS2;
        public InputAction @B2 => m_Wrapper.m_Piano_B2;
        public InputAction @C3 => m_Wrapper.m_Piano_C3;
        public InputAction @CS3 => m_Wrapper.m_Piano_CS3;
        public InputAction @D3 => m_Wrapper.m_Piano_D3;
        public InputAction @DS3 => m_Wrapper.m_Piano_DS3;
        public InputAction @E3 => m_Wrapper.m_Piano_E3;
        public InputAction @F3 => m_Wrapper.m_Piano_F3;
        public InputAction @FS3 => m_Wrapper.m_Piano_FS3;
        public InputAction @G3 => m_Wrapper.m_Piano_G3;
        public InputAction @GS3 => m_Wrapper.m_Piano_GS3;
        public InputAction @A3 => m_Wrapper.m_Piano_A3;
        public InputAction @AS3 => m_Wrapper.m_Piano_AS3;
        public InputAction @B3 => m_Wrapper.m_Piano_B3;
        public InputAction @C4 => m_Wrapper.m_Piano_C4;
        public InputAction @CS4 => m_Wrapper.m_Piano_CS4;
        public InputAction @D4 => m_Wrapper.m_Piano_D4;
        public InputAction @DS4 => m_Wrapper.m_Piano_DS4;
        public InputAction @E4 => m_Wrapper.m_Piano_E4;
        public InputAction @F4 => m_Wrapper.m_Piano_F4;
        public InputAction @FS4 => m_Wrapper.m_Piano_FS4;
        public InputAction @G4 => m_Wrapper.m_Piano_G4;
        public InputAction @GS4 => m_Wrapper.m_Piano_GS4;
        public InputAction @A4 => m_Wrapper.m_Piano_A4;
        public InputAction @AS4 => m_Wrapper.m_Piano_AS4;
        public InputAction @B4 => m_Wrapper.m_Piano_B4;
        public InputActionMap Get() { return m_Wrapper.m_Piano; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PianoActions set) { return set.Get(); }
        public void SetCallbacks(IPianoActions instance)
        {
            if (m_Wrapper.m_PianoActionsCallbackInterface != null)
            {
                @C2.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnC2;
                @C2.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnC2;
                @C2.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnC2;
                @CS2.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS2;
                @CS2.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS2;
                @CS2.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS2;
                @D2.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnD2;
                @D2.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnD2;
                @D2.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnD2;
                @DS2.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS2;
                @DS2.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS2;
                @DS2.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS2;
                @E2.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnE2;
                @E2.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnE2;
                @E2.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnE2;
                @F2.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnF2;
                @F2.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnF2;
                @F2.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnF2;
                @FS2.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnFS2;
                @FS2.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnFS2;
                @FS2.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnFS2;
                @G2.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnG2;
                @G2.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnG2;
                @G2.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnG2;
                @GS2.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnGS2;
                @GS2.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnGS2;
                @GS2.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnGS2;
                @A2.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnA2;
                @A2.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnA2;
                @A2.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnA2;
                @AS2.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnAS2;
                @AS2.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnAS2;
                @AS2.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnAS2;
                @B2.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnB2;
                @B2.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnB2;
                @B2.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnB2;
                @C3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnC3;
                @C3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnC3;
                @C3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnC3;
                @CS3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS3;
                @CS3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS3;
                @CS3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS3;
                @D3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnD3;
                @D3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnD3;
                @D3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnD3;
                @DS3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS3;
                @DS3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS3;
                @DS3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS3;
                @E3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnE3;
                @E3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnE3;
                @E3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnE3;
                @F3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnF3;
                @F3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnF3;
                @F3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnF3;
                @FS3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnFS3;
                @FS3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnFS3;
                @FS3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnFS3;
                @G3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnG3;
                @G3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnG3;
                @G3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnG3;
                @GS3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnGS3;
                @GS3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnGS3;
                @GS3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnGS3;
                @A3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnA3;
                @A3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnA3;
                @A3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnA3;
                @AS3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnAS3;
                @AS3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnAS3;
                @AS3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnAS3;
                @B3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnB3;
                @B3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnB3;
                @B3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnB3;
                @C4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnC4;
                @C4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnC4;
                @C4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnC4;
                @CS4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS4;
                @CS4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS4;
                @CS4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS4;
                @D4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnD4;
                @D4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnD4;
                @D4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnD4;
                @DS4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS4;
                @DS4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS4;
                @DS4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS4;
                @E4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnE4;
                @E4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnE4;
                @E4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnE4;
                @F4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnF4;
                @F4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnF4;
                @F4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnF4;
                @FS4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnFS4;
                @FS4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnFS4;
                @FS4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnFS4;
                @G4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnG4;
                @G4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnG4;
                @G4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnG4;
                @GS4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnGS4;
                @GS4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnGS4;
                @GS4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnGS4;
                @A4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnA4;
                @A4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnA4;
                @A4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnA4;
                @AS4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnAS4;
                @AS4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnAS4;
                @AS4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnAS4;
                @B4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnB4;
                @B4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnB4;
                @B4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnB4;
            }
            m_Wrapper.m_PianoActionsCallbackInterface = instance;
            if (instance != null)
            {
                @C2.started += instance.OnC2;
                @C2.performed += instance.OnC2;
                @C2.canceled += instance.OnC2;
                @CS2.started += instance.OnCS2;
                @CS2.performed += instance.OnCS2;
                @CS2.canceled += instance.OnCS2;
                @D2.started += instance.OnD2;
                @D2.performed += instance.OnD2;
                @D2.canceled += instance.OnD2;
                @DS2.started += instance.OnDS2;
                @DS2.performed += instance.OnDS2;
                @DS2.canceled += instance.OnDS2;
                @E2.started += instance.OnE2;
                @E2.performed += instance.OnE2;
                @E2.canceled += instance.OnE2;
                @F2.started += instance.OnF2;
                @F2.performed += instance.OnF2;
                @F2.canceled += instance.OnF2;
                @FS2.started += instance.OnFS2;
                @FS2.performed += instance.OnFS2;
                @FS2.canceled += instance.OnFS2;
                @G2.started += instance.OnG2;
                @G2.performed += instance.OnG2;
                @G2.canceled += instance.OnG2;
                @GS2.started += instance.OnGS2;
                @GS2.performed += instance.OnGS2;
                @GS2.canceled += instance.OnGS2;
                @A2.started += instance.OnA2;
                @A2.performed += instance.OnA2;
                @A2.canceled += instance.OnA2;
                @AS2.started += instance.OnAS2;
                @AS2.performed += instance.OnAS2;
                @AS2.canceled += instance.OnAS2;
                @B2.started += instance.OnB2;
                @B2.performed += instance.OnB2;
                @B2.canceled += instance.OnB2;
                @C3.started += instance.OnC3;
                @C3.performed += instance.OnC3;
                @C3.canceled += instance.OnC3;
                @CS3.started += instance.OnCS3;
                @CS3.performed += instance.OnCS3;
                @CS3.canceled += instance.OnCS3;
                @D3.started += instance.OnD3;
                @D3.performed += instance.OnD3;
                @D3.canceled += instance.OnD3;
                @DS3.started += instance.OnDS3;
                @DS3.performed += instance.OnDS3;
                @DS3.canceled += instance.OnDS3;
                @E3.started += instance.OnE3;
                @E3.performed += instance.OnE3;
                @E3.canceled += instance.OnE3;
                @F3.started += instance.OnF3;
                @F3.performed += instance.OnF3;
                @F3.canceled += instance.OnF3;
                @FS3.started += instance.OnFS3;
                @FS3.performed += instance.OnFS3;
                @FS3.canceled += instance.OnFS3;
                @G3.started += instance.OnG3;
                @G3.performed += instance.OnG3;
                @G3.canceled += instance.OnG3;
                @GS3.started += instance.OnGS3;
                @GS3.performed += instance.OnGS3;
                @GS3.canceled += instance.OnGS3;
                @A3.started += instance.OnA3;
                @A3.performed += instance.OnA3;
                @A3.canceled += instance.OnA3;
                @AS3.started += instance.OnAS3;
                @AS3.performed += instance.OnAS3;
                @AS3.canceled += instance.OnAS3;
                @B3.started += instance.OnB3;
                @B3.performed += instance.OnB3;
                @B3.canceled += instance.OnB3;
                @C4.started += instance.OnC4;
                @C4.performed += instance.OnC4;
                @C4.canceled += instance.OnC4;
                @CS4.started += instance.OnCS4;
                @CS4.performed += instance.OnCS4;
                @CS4.canceled += instance.OnCS4;
                @D4.started += instance.OnD4;
                @D4.performed += instance.OnD4;
                @D4.canceled += instance.OnD4;
                @DS4.started += instance.OnDS4;
                @DS4.performed += instance.OnDS4;
                @DS4.canceled += instance.OnDS4;
                @E4.started += instance.OnE4;
                @E4.performed += instance.OnE4;
                @E4.canceled += instance.OnE4;
                @F4.started += instance.OnF4;
                @F4.performed += instance.OnF4;
                @F4.canceled += instance.OnF4;
                @FS4.started += instance.OnFS4;
                @FS4.performed += instance.OnFS4;
                @FS4.canceled += instance.OnFS4;
                @G4.started += instance.OnG4;
                @G4.performed += instance.OnG4;
                @G4.canceled += instance.OnG4;
                @GS4.started += instance.OnGS4;
                @GS4.performed += instance.OnGS4;
                @GS4.canceled += instance.OnGS4;
                @A4.started += instance.OnA4;
                @A4.performed += instance.OnA4;
                @A4.canceled += instance.OnA4;
                @AS4.started += instance.OnAS4;
                @AS4.performed += instance.OnAS4;
                @AS4.canceled += instance.OnAS4;
                @B4.started += instance.OnB4;
                @B4.performed += instance.OnB4;
                @B4.canceled += instance.OnB4;
            }
        }
    }
    public PianoActions @Piano => new PianoActions(this);
    public interface IPianoActions
    {
        void OnC2(InputAction.CallbackContext context);
        void OnCS2(InputAction.CallbackContext context);
        void OnD2(InputAction.CallbackContext context);
        void OnDS2(InputAction.CallbackContext context);
        void OnE2(InputAction.CallbackContext context);
        void OnF2(InputAction.CallbackContext context);
        void OnFS2(InputAction.CallbackContext context);
        void OnG2(InputAction.CallbackContext context);
        void OnGS2(InputAction.CallbackContext context);
        void OnA2(InputAction.CallbackContext context);
        void OnAS2(InputAction.CallbackContext context);
        void OnB2(InputAction.CallbackContext context);
        void OnC3(InputAction.CallbackContext context);
        void OnCS3(InputAction.CallbackContext context);
        void OnD3(InputAction.CallbackContext context);
        void OnDS3(InputAction.CallbackContext context);
        void OnE3(InputAction.CallbackContext context);
        void OnF3(InputAction.CallbackContext context);
        void OnFS3(InputAction.CallbackContext context);
        void OnG3(InputAction.CallbackContext context);
        void OnGS3(InputAction.CallbackContext context);
        void OnA3(InputAction.CallbackContext context);
        void OnAS3(InputAction.CallbackContext context);
        void OnB3(InputAction.CallbackContext context);
        void OnC4(InputAction.CallbackContext context);
        void OnCS4(InputAction.CallbackContext context);
        void OnD4(InputAction.CallbackContext context);
        void OnDS4(InputAction.CallbackContext context);
        void OnE4(InputAction.CallbackContext context);
        void OnF4(InputAction.CallbackContext context);
        void OnFS4(InputAction.CallbackContext context);
        void OnG4(InputAction.CallbackContext context);
        void OnGS4(InputAction.CallbackContext context);
        void OnA4(InputAction.CallbackContext context);
        void OnAS4(InputAction.CallbackContext context);
        void OnB4(InputAction.CallbackContext context);
    }
}
